FROM postgres:15

# Imposta le variabili d'ambiente per configurare il database (possono essere sovrascritte)
ENV POSTGRES_USER=test
ENV POSTGRES_PASSWORD=test
ENV POSTGRES_DB=test

# Espone la porta di default di PostgreSQL
EXPOSE 5432

# Avvia PostgreSQL
CMD ["postgres"]